require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FanPagesController do

  # This should return the minimal set of attributes required to create a valid
  # FanPage. As you add validations to FanPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FanPagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all fan_pages as @fan_pages" do
      fan_page = FanPage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fan_pages).should eq([fan_page])
    end
  end

  describe "GET show" do
    it "assigns the requested fan_page as @fan_page" do
      fan_page = FanPage.create! valid_attributes
      get :show, {:id => fan_page.to_param}, valid_session
      assigns(:fan_page).should eq(fan_page)
    end
  end

  describe "GET new" do
    it "assigns a new fan_page as @fan_page" do
      get :new, {}, valid_session
      assigns(:fan_page).should be_a_new(FanPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested fan_page as @fan_page" do
      fan_page = FanPage.create! valid_attributes
      get :edit, {:id => fan_page.to_param}, valid_session
      assigns(:fan_page).should eq(fan_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FanPage" do
        expect {
          post :create, {:fan_page => valid_attributes}, valid_session
        }.to change(FanPage, :count).by(1)
      end

      it "assigns a newly created fan_page as @fan_page" do
        post :create, {:fan_page => valid_attributes}, valid_session
        assigns(:fan_page).should be_a(FanPage)
        assigns(:fan_page).should be_persisted
      end

      it "redirects to the created fan_page" do
        post :create, {:fan_page => valid_attributes}, valid_session
        response.should redirect_to(FanPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fan_page as @fan_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        FanPage.any_instance.stub(:save).and_return(false)
        post :create, {:fan_page => {}}, valid_session
        assigns(:fan_page).should be_a_new(FanPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FanPage.any_instance.stub(:save).and_return(false)
        post :create, {:fan_page => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fan_page" do
        fan_page = FanPage.create! valid_attributes
        # Assuming there are no other fan_pages in the database, this
        # specifies that the FanPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FanPage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => fan_page.to_param, :fan_page => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested fan_page as @fan_page" do
        fan_page = FanPage.create! valid_attributes
        put :update, {:id => fan_page.to_param, :fan_page => valid_attributes}, valid_session
        assigns(:fan_page).should eq(fan_page)
      end

      it "redirects to the fan_page" do
        fan_page = FanPage.create! valid_attributes
        put :update, {:id => fan_page.to_param, :fan_page => valid_attributes}, valid_session
        response.should redirect_to(fan_page)
      end
    end

    describe "with invalid params" do
      it "assigns the fan_page as @fan_page" do
        fan_page = FanPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FanPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => fan_page.to_param, :fan_page => {}}, valid_session
        assigns(:fan_page).should eq(fan_page)
      end

      it "re-renders the 'edit' template" do
        fan_page = FanPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FanPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => fan_page.to_param, :fan_page => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fan_page" do
      fan_page = FanPage.create! valid_attributes
      expect {
        delete :destroy, {:id => fan_page.to_param}, valid_session
      }.to change(FanPage, :count).by(-1)
    end

    it "redirects to the fan_pages list" do
      fan_page = FanPage.create! valid_attributes
      delete :destroy, {:id => fan_page.to_param}, valid_session
      response.should redirect_to(fan_pages_url)
    end
  end

end
